### ISSUE TITLE
Returned paths are (mostly) not in unified format

### ISSUE THREAD

**Issue by j-o** [cginternals/cpplocate#38]
The docs for `getModulePath`, `getLibraryPath`, and `locatePath` all specify `The path is returned in unified format (forward slashes).`, but none of them actually do any conversion. Which is wrong, the docs or the implementations?

**Comment by sbusch42** [comment]
I would say the docs are wrong. I think it's okay when the library returns paths in native format, since it mostly directly calls native system functions. In case of the functions on top, the returned paths are a mixture of native format and forward slashes, but this is also valid for all supported systems. So I say let's just remove the remarks from the docs.

**Comment by j-o** [comment]
`getBundlePath` actually does this conversion via `unifyPathDelimiters` utility function. Should this be removed then? If yes, the whole utility function is obsolete since this is the only usage and it is not part of the public API.
