### ISSUE TITLE
Mac Bundle Path tests fail and possible bug

### ISSUE THREAD

**Issue by ekilmer** [cginternals/cpplocate#45]
I noticed that I get failures regarding bundle path when running the tests on Mac.

```
[  FAILED  ] liblocate_test.getBundlePath_Return
```

After adding `MACOSX_BUNDLE` to CMake `add_executable` (tests still work on Linux with this), I also noticed a potential bug in the code with regards to the return of the path, but I'm not sure if my fix is totally correct, or even necessary. I tried looking at the pattern of another function and now the tests pass. The following diff seems to fix it? I can open a PR as well.

```diff
diff --git a/source/liblocate/source/liblocate.c b/source/liblocate/source/liblocate.c
index 2e53d56..b98155c 100644
--- a/source/liblocate/source/liblocate.c
+++ b/source/liblocate/source/liblocate.c
@@ -207,11 +207,9 @@ void getBundlePath(char ** path, unsigned int * pathLength)
     }

     // Copy contents to caller, create caller ownership
-    *path = executablePath;
-    if (pathLength != 0x0)
-    {
-        *pathLength = bundlePathLength;
-    }
+    copyToStringOutParameter(executablePath, bundlePathLength, path, pathLength);
+
+    free(executablePath);
 }

 void getModulePath(char ** path, unsigned int * pathLength)
diff --git a/source/tests/cpplocate-test/CMakeLists.txt b/source/tests/cpplocate-test/CMakeLists.txt
index 2197b5d..1c02a2a 100644
--- a/source/tests/cpplocate-test/CMakeLists.txt
+++ b/source/tests/cpplocate-test/CMakeLists.txt
@@ -30,7 +30,7 @@ set(sources
 #

 # Build executable
-add_executable(${target}
+add_executable(${target} MACOSX_BUNDLE
     ${sources}
 )

diff --git a/source/tests/liblocate-test/CMakeLists.txt b/source/tests/liblocate-test/CMakeLists.txt
index 3bc2363..189f6cf 100644
--- a/source/tests/liblocate-test/CMakeLists.txt
+++ b/source/tests/liblocate-test/CMakeLists.txt
@@ -34,7 +34,7 @@ set(sources
 #

 # Build executable
-add_executable(${target}
+add_executable(${target} MACOSX_BUNDLE
     ${sources}
 )
```

**Comment by scheibel** [comment]
Thanks for reporting. I had a look at it and eventually found the bug.

We assumed in the tests that the contents of the out-parameter `path` are a C-string with a `0` delimiter at the end of the string (something sensible to assume, I think). However, in the implementation we tried to save a copy by reusing the results from `getExecutablePath` which the function `getBundlePath` takes ownership of. Through passing the position as a second out parameter this function is somewhat usable, but plain C functions as `strlen` would see the whole executable path instead of just the bundle part.
Concluding: Yes, your code actually fixes the code.

Note: I could reproduce this error even on linux when removing the `ifdefs` in `TEST_F(liblocate_test, getBundlePath_Return)`.
